Feature organisation
TheCodexProject/TheCodexProject-BackEnd pull request #10
Opened 2024-09-27 09:30 UTC by MalasataXD

### Organisation
___
Here is the basic concept for the Organisation Model. This includes:
- `OrganisationName`
- Exceptions related to the `OrganisationName`
- `IOwnership` interface to indicate which class can own others.
- `Organisation` ← This is the actual implementation.
- `OrganisationBuilder` - a builder for the `Organisation`.
- Tests related to the `OrganisationBuilder`.
- `Workspace` changes, it can now be owned by either a `Organisation` or `User`.

2024-09-27 13:31 UTC, BjarkeBP requested changes
Some mior changes is required.

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/exceptions/Organisation/OrganisationNameEmptyException.cs
> +/// Exception for when a WorkItem is created without a title.
Not a WorkItem

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/Organisation.cs
> +    public Id<Organisation> Id { get; }
Can be taken out and add or remove to.  can be done like this

```
     /// <summary>
    /// Holds a private list of filter expressions used to filter WorkItems.
    /// </summary>
    private readonly List<FilterExpression> _filters = new List<FilterExpression>();

    /// <summary>
    /// Exposes a read-only view of filter expressions.
    /// </summary>
    public IEnumerable<FilterExpression> Filters => _filters.AsReadOnly();
    ```

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/Organisation.cs
> +    public List<IOwnership>? Owners { get; }
Same as above

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/Organisation.cs
> +    // public IEnumerable<Documentation> Docs { get; }
This PR should wait ontil documentation is ready?

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/Organisation.cs
Can a owner not be removed?

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/OrganisationBuilder.cs
> +        // ? Check if there are any WorkItemTitleEmptyExceptions in the errors list.
Should not be WorkItemTitleEmptyExceptions

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/OrganisationBuilder.cs
> +            // * Take out the WorkItemTitleEmptyException from errors and store it in a variable.
Should not be WorkItemTitleEmptyException

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/OrganisationBuilder.cs
> +            // * Remove the WorkItemTitleEmptyException from the errors list.
Should not be WorkItemTitleEmptyException

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/OrganisationBuilder.cs
> +            // * Create a new RequiredFieldMissingException with the WorkItemTitleEmptyException as the inner exception.
Should not be WorkItemTitleEmptyException

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/User/User.cs
> +public class User : IOwnership
Fixing other things then organisation 😉 (pog)

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Workspace/Workspace.cs
> +    public IOwnership Owner { get; private set; }
Very nice, thx you

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Workspace/WorkspaceConstants.cs
> +    public static readonly User DefaultOwner = User.Create();
There might come changes so use the MakeDefault()

2024-09-27 13:31 UTC, BjarkeBP commented on src/core/domain/models/Organisation/OrganisationBuilder.cs
Should owner be required?

2024-09-27 13:31 UTC, BjarkeBP commented on src/tests/Unit/values/Organisation/OrganisationNameTests.cs
> +        var name = "Organisation";
Make a OrganisationConstants for values to test

2024-09-27 13:37 UTC, MalasataXD commented on src/core/domain/models/Organisation/Organisation.cs
> +    public Id<Organisation> Id { get; }
Well... It can be taken out, but that is FOR SURE not the solution xD

2024-09-27 13:40 UTC, BjarkeBP commented on src/core/domain/models/Organisation/Organisation.cs
> +    public Id<Organisation> Id { get; }
Does .AsReadOnly() not fix the problem?
Please share if there is a better way to do it (I need it for my code 😅)

2024-09-27 13:42 UTC, MalasataXD commented on src/core/domain/models/Organisation/Organisation.cs
> +    public Id<Organisation> Id { get; }
Well... I was just referring to that would fix the problem with Organisation, since it doesn't have any filters 😉

2024-09-27 13:45 UTC, BjarkeBP commented on src/core/domain/models/Organisation/Organisation.cs
> +    public Id<Organisation> Id { get; }
oohh haha, i see. It was just a example 🫠💀

2024-09-27 13:53 UTC, MalasataXD commented on src/core/domain/models/Workspace/WorkspaceConstants.cs
> +    public static readonly User DefaultOwner = User.Create();
Then it would introduce a reliability on the `UserBuilder`. So I think an empty `User` will suffice this use.

2024-09-27 13:57 UTC, MalasataXD commented on src/tests/Unit/values/Organisation/OrganisationNameTests.cs
> +        var name = "Organisation";
I would say that doesn't apply to the scenario being tested. This is supposed to **not** be a value that is default, as it just tests that you are able to name the organisation using the builder 😉

2024-09-27 14:01 UTC, MalasataXD commented on src/core/domain/models/User/User.cs
> +public class User : IOwnership
Nope, this was related to the Organisation feature, as we discussed Monday. 😉 
Since this introduces the `IOwnership` interface, and we agreed upon that it needed to be added to both User and Workspace when I added it 👍

2024-09-27 14:01 UTC, MalasataXD commented on src/core/domain/models/Workspace/Workspace.cs
> +    public IOwnership Owner { get; private set; }
Same as for above 😉

2024-09-30 10:38 UTC, BjarkeBP requested changes
Looks good, only something to be considered.

2024-09-30 10:38 UTC, BjarkeBP commented on src/core/domain/models/Organisation/OrganisationBuilder.cs
> +            var requiredFieldMissingException = new RequiredFieldMissingException("Name is required. 1",error);
Remove the "1" in the exception

2024-09-30 10:38 UTC, BjarkeBP commented on src/tests/Unit/models/Organisation/OrganisationBuilderTests.cs
Should there be tested if the builder returns a RequiredFieldMissingException instead of OrganisationNameEmptyException

2024-09-30 12:45 UTC, BjarkeBP approved these changes
Looks good to me ^_____^

2024-09-30 12:46 UTC, Grey-rgb approved these changes
🍇 👍

2024-09-30 13:04 UTC, merged