Improvement workitem
TheCodexProject/TheCodexProject-BackEnd pull request #11
Opened 2024-09-27 09:53 UTC by MalasataXD

### WorkItem
___
This improvement adds the ability to now have both Sub-items and Dependencies for the WorkItem.
- Sub-Items are other work items that need to be completed to complete the "Parent" work item.
- Dependencies are other tasks that need to be completed before the given work item can be started.

2024-09-27 12:47 UTC, BjarkeBP requested changes
Some minor change is required

2024-09-27 12:47 UTC, BjarkeBP commented on src/core/domain/models/WorkItem/WorkItem.cs
> +    // public List<Documentation> Documentations { get; private set; }
I think this PR should wait and get the documentation part with it now

2024-09-27 12:47 UTC, BjarkeBP commented on src/core/domain/models/WorkItem/WorkItem.cs
> +    public List<WorkItem> SubItems { get; private set; }
I can get this and modified it. (add and remove from the list)

2024-09-27 12:47 UTC, BjarkeBP commented on src/core/domain/models/WorkItem/WorkItem.cs
> +    public List<Id<WorkItem>> Dependencies { get; private set; }
I can get this and modified it. (add and remove from the list)

2024-09-27 12:47 UTC, BjarkeBP commented on src/core/domain/models/WorkItem/WorkItem.cs
> +    public Result RemoveSubItem(WorkItem item)
Should this not return something ellers if the item does not exist in the list?

2024-09-27 12:47 UTC, BjarkeBP commented on src/core/domain/models/WorkItem/WorkItem.cs
> +    public Result RemoveDependency(Id<WorkItem> item)
Should this not return something ellers if the item does not exist in the list?

2024-09-27 12:47 UTC, BjarkeBP commented on src/core/domain/models/WorkItem/WorkItemConstants.cs
> +        WorkItem.Create(),
This might get some required fields, so it should use MakeDefault()

2024-09-27 13:07 UTC, MalasataXD commented on src/core/domain/models/WorkItem/WorkItemConstants.cs
> +        WorkItem.Create(),
That wouldn't make sense to use within the Constants class, since if then `MakeDefault()` would depend on itself. This would be a circular dependency...

2024-09-27 13:36 UTC, BjarkeBP commented on src/core/domain/models/WorkItem/WorkItemConstants.cs
> +        WorkItem.Create(),
Nvm my bad, thought it was for a obj outside the constants. Might have gone throught it too quick XDXD

2024-09-30 11:06 UTC, Grey-rgb requested changes
Looks good, but just a minor little thing needs to be changed.

2024-09-30 12:51 UTC, BjarkeBP approved these changes
Looks good to me.

2024-09-30 12:54 UTC, Grey-rgb approved these changes
LGTM 👍

2024-09-30 13:05 UTC, merged