Feature milestone
TheCodexProject/TheCodexProject-BackEnd pull request #12
Opened 2024-09-27 09:56 UTC by Grey-rgb

* Added MilestoneTitle
* Added MilestoneTitle tests

* Added MilestoneWorkitem
* Added MilestoneWorkitem tests

* Added MilestoneBuilder
* Added MilestoneBuilder tests

2024-09-27 10:24 UTC, MalasataXD requested changes

2024-09-27 10:24 UTC, MalasataXD commented on src/core/domain/models/Milestone/Milestone.cs
> +    public void AddWorkItem(WorkItem workItem)
Use the Result return type

2024-09-27 10:24 UTC, MalasataXD commented on src/tests/Unit/values/Milestone/MilestoneWorkItemsTests.cs
> +            // Assert
Remember to check that the Result is a success.

2024-09-27 12:36 UTC, BjarkeBP requested changes
Some minor change is required

2024-09-27 12:36 UTC, BjarkeBP commented on src/core/domain/exceptions/Milestone/MilestoneTitle/MilestoneTitleEmptyException.cs
> +/// Exception for when a Project is created without a title.
The summary does not match the domain item

2024-09-27 12:36 UTC, BjarkeBP commented on src/core/domain/models/Milestone/Milestone.cs
> +    public List<Id<WorkItem>> WorkItems => _workItems;
Add this part to make sure that it's not modified
_workItems.AsReadOnly();

2024-09-27 12:36 UTC, BjarkeBP commented on src/core/domain/models/Milestone/Milestone.cs
> +            throw new ArgumentNullException(nameof(workItem));
Should this be a custom Exception?

2024-09-30 07:03 UTC, MalasataXD requested changes
There still a few things to be desired... Otherwise nicely done.

2024-09-30 07:03 UTC, MalasataXD commented on src/core/domain/models/Milestone/MilestoneBuilder.cs
No method for adding `WorkItems` from the Builder? This might just be a "nice-to-have" functionality.

2024-09-30 09:34 UTC, MalasataXD requested changes
Just two things to go! 👍

2024-09-30 09:34 UTC, MalasataXD commented on src/core/domain/exceptions/Milestone/MilestoneWorkItemErrorException.cs
> +public class MilestoneWorkItemErrorException : Exception
Please remove this and use **only** `MilestoneWorkItemNotFoundException`.

2024-09-30 09:34 UTC, MalasataXD commented on src/core/domain/models/Milestone/Milestone.cs
> +            return Result.Failure(new MilestoneWorkItemErrorException());
Use `MilestoneWorkItemNotFoundException` instead of `MilestoneWorkItemErrorException`

2024-09-30 11:36 UTC, MalasataXD requested changes
Just 1 thing to go 😉

2024-09-30 11:36 UTC, MalasataXD commented on src/core/domain/models/Milestone/Milestone.cs
>              return Result.Failure(new MilestoneWorkItemNotFoundException());
Missing the text in the exception telling that the work items are null.

2024-09-30 11:48 UTC, MalasataXD approved these changes
Looks ready to merge 🐕

2024-09-30 11:49 UTC, BjarkeBP approved these changes
Looks good to me 😊

2024-09-30 11:56 UTC, merged