Feature iteration
TheCodexProject/TheCodexProject-BackEnd pull request #7
Opened 2024-09-26 15:34 UTC by BjarkeBP

Added
- model + values with tests
- Builder with tests
- Constants

2024-09-26 18:43 UTC, MalasataXD requested changes
Just a few minor things, otherwise it looks good. Nice Job! 👍

2024-09-26 18:43 UTC, MalasataXD commented on src/core/domain/models/Iteration/Iteration.cs
> +    public IEnumerable<Id<WorkItem>> WorkItems => _workItems;
Choose either... This seems a little like clutter. I would personally just like the `List<Id<WorkItem>>`.  😉 
I know I just wrote the interface on the "class diagram".

2024-09-26 18:43 UTC, MalasataXD commented on src/core/domain/models/Iteration/Iteration.cs
> +            return Result.Failure();
Shouldn't it return some kind of exception to let you know what happened? I think that would make some sense.

2024-09-26 18:43 UTC, MalasataXD commented on src/core/domain/models/Iteration/IterationBuilder.cs
It would be nice to be able to just connect some `WorkItem`s directly from the builder. But maybe that is just a "nice-to-have" functionality idk.

2024-09-26 18:43 UTC, MalasataXD commented on src/tests/Unit/values/Iteration/IterationTitleTests.cs
> +    public void Title_Can_Be_Created_With_75_Characters()
This test doesn't match with the description. Is that a mistake or the description is just off?

2024-09-27 12:10 UTC, BjarkeBP commented on src/core/domain/models/Iteration/Iteration.cs
> +    public IEnumerable<Id<WorkItem>> WorkItems => _workItems;
i might do it like this, would that be okay. It's so people can't do things with my list.
Don't mind that the names are from board

```
/// <summary>
/// Exposes a read-only view of filter expressions.
/// </summary>
public IEnumerable<FilterExpression> Filters => _filters.AsReadOnly();

/// <summary>
/// Exposes a read-only view of order-by expressions.
/// </summary>
public IEnumerable<OrderByExpression> OrderByExpressions => _orderByExpressions.AsReadOnly();
```

2024-09-27 12:13 UTC, BjarkeBP commented on src/core/domain/models/Iteration/Iteration.cs
> +            return Result.Failure();
I have done this a couple of places, should we make a overall not found exception? or have some sort of convention

2024-09-27 12:15 UTC, MalasataXD commented on src/core/domain/models/Iteration/Iteration.cs
> +            return Result.Failure();
Sure. Just make shared NotFound exception... We are going to need one for the repositories later anyway.

2024-09-27 12:16 UTC, BjarkeBP commented on src/core/domain/models/Iteration/IterationBuilder.cs
Depends, are we going to promp the user for all inputs? Or are we going to make it so it creates a empty iteration, and then they can add workItems to it

2024-09-27 12:17 UTC, BjarkeBP commented on src/tests/Unit/values/Iteration/IterationTitleTests.cs
> +    public void Title_Can_Be_Created_With_75_Characters()
Hehe my bad. 
Ctrl c, Ctrl v.

2024-09-30 10:59 UTC, MalasataXD requested changes
A minor thing, but otherwise 😉

2024-09-30 10:59 UTC, MalasataXD commented on src/core/domain/models/Iteration/Iteration.cs
> +            return Result.Failure(new IteractionWorkItemNullException());
Just a minor thing... I would like that you use `IterationWorkItemNotFound("The given work item is null")`, Instead since to "errors" are related to each other.

2024-09-30 10:59 UTC, MalasataXD commented on src/core/domain/models/Iteration/Iteration.cs
> +            return Result.Failure(new IteractionWorkItemNullException());
Same for this one.

2024-09-30 11:13 UTC, Grey-rgb requested changes
💀

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IteractionWorkItemNullException.cs
> +public class IteractionWorkItemNullException : Exception
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IteractionWorkItemNullException.cs
> +    public IteractionWorkItemNullException() : base("WorkItem cannot be null") { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IteractionWorkItemNullException.cs
> +    public IteractionWorkItemNullException(string message) : base(message) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IteractionWorkItemNullException.cs
> +    public IteractionWorkItemNullException(string message, Exception innerException) : base(message, innerException) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IteractionWorkItemNullException.cs
> +    protected IteractionWorkItemNullException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleEmptyException.cs
> +    public IterationTitleEmptyException() : base("Title cannot be empty, it must be between 3 and 75 characters.") { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleEmptyException.cs
> +    public IterationTitleEmptyException(string message) : base(message) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleEmptyException.cs
> +    public IterationTitleEmptyException(string message, Exception innerException) : base(message, innerException) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleEmptyException.cs
> +    protected IterationTitleEmptyException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooLongException.cs
> +    public IterationTitleTooLongException() : base("Title cannot be more then 75 characters") { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooLongException.cs
> +    public IterationTitleTooLongException(string message) : base(message) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooLongException.cs
> +    public IterationTitleTooLongException(string message, Exception innerException) : base(message, innerException) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooLongException.cs
> +    protected IterationTitleTooLongException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooShortException.cs
> +    public IterationTitleTooShortException() : base("Title is too short, it must be more then 3 characters.") { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooShortException.cs
> +    public IterationTitleTooShortException(string message) : base(message) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooShortException.cs
> +    public IterationTitleTooShortException(string message, Exception innerException) : base(message, innerException) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationTitle/IterationTitleTooShortException.cs
> +    protected IterationTitleTooShortException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemAlreadyExistsException.cs
> +    public IterationWorkItemAlreadyExistsException() : base("WorkItem already exists in the iteration") { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemAlreadyExistsException.cs
> +    public IterationWorkItemAlreadyExistsException(string message) : base(message) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemAlreadyExistsException.cs
> +    public IterationWorkItemAlreadyExistsException(string message, Exception innerException) : base(message, innerException) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemAlreadyExistsException.cs
> +    protected IterationWorkItemAlreadyExistsException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemNotFoundException.cs
> +    public IterationWorkItemNotFoundException() : base("WorkItem not found in Iteration") { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemNotFoundException.cs
> +    public IterationWorkItemNotFoundException(string message) : base(message) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemNotFoundException.cs
> +    public IterationWorkItemNotFoundException(string message, Exception innerException) : base(message, innerException) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, Grey-rgb commented on src/core/domain/exceptions/Iteration/IterationWorkItemNotFoundException.cs
> +    protected IterationWorkItemNotFoundException(SerializationInfo info, StreamingContext context) : base(info, context) { }
Actually it's not Interaction, but Iteration

2024-09-30 11:13 UTC, BjarkeBP commented on src/core/domain/models/Iteration/Iteration.cs
> +            return Result.Failure(new IteractionWorkItemNullException());
@Grey-rgb what do you think about this

2024-09-30 11:13 UTC, BjarkeBP commented on src/core/domain/models/Iteration/Iteration.cs
> +            return Result.Failure(new IteractionWorkItemNullException());
@Grey-rgb what do you think about this

2024-09-30 11:25 UTC, MalasataXD approved these changes
Looks ready to merge 🦙

2024-09-30 11:28 UTC, Grey-rgb approved these changes
LGTM

2024-09-30 11:28 UTC, merged