Added all the stuff to the Board feature.
TheCodexProject/TheCodexProject-BackEnd pull request #8
Opened 2024-09-26 17:48 UTC by BjarkeBP

Added exceptions, model, builder, constants and test for the board feature

2024-09-26 19:00 UTC, MalasataXD requested changes
Just a few things, that I maybe just need to be explained. But otherwise it looks good 👍

2024-09-26 19:00 UTC, MalasataXD commented on src/core/domain/exceptions/Workspace/WorkspaceTitle/WorkspaceTitleTooShortException.cs
Oh damn! He has fixed something other that boards.... -rep xD

2024-09-26 19:00 UTC, MalasataXD commented on src/core/domain/models/Board/Board.cs
> +        public BoardQuery Query { get; private set; }
Why is this not nullable, when the Title is?

2024-09-26 19:00 UTC, MalasataXD commented on src/core/domain/models/Board/Board.cs
> +        public BoardQuery Query { get; private set; }
Also have you tested that this actually works? I am really in doubt about this working...

2024-09-26 19:00 UTC, MalasataXD commented on src/tests/Unit/models/Board/BoardBuilderTests.cs
> +    public void BoardBuilder_Changes_BoardTitleEmptyException_To_RequiredFieldMissingException()
Why haven't this been done for `BoardQuery` as well? Since that would also be an exception in the list in this scenario right?

2024-09-27 06:02 UTC, BjarkeBP commented on src/core/domain/exceptions/Workspace/WorkspaceTitle/WorkspaceTitleTooShortException.cs
Hehe 😅

2024-09-27 06:03 UTC, BjarkeBP commented on src/core/domain/models/Board/Board.cs
> +        public BoardQuery Query { get; private set; }
Good point, will change it to nullable and add a test for it.

2024-09-27 06:05 UTC, BjarkeBP commented on src/tests/Unit/models/Board/BoardBuilderTests.cs
> +    public void BoardBuilder_Changes_BoardTitleEmptyException_To_RequiredFieldMissingException()
Sure, I'll make a test for that.

2024-09-27 06:19 UTC, BjarkeBP commented on src/core/domain/models/Board/Board.cs
> +        public BoardQuery Query { get; private set; }
Okay so i some what have a unit test for it `BoardBuilder_Builds_With_No_Query_Fails`
But i don't get why it lets me use the create function when it have a field that isn't nullable

2024-09-30 06:31 UTC, MalasataXD requested changes
There are just a few things that need to be looked at in regards to `Filters` and `OrderBy` Expressions. Otherwise Nice work man! 👍

2024-09-30 06:31 UTC, MalasataXD commented on src/core/domain/models/Board/Board.cs
> +    #region Filter Methods
Why the region? It is only two methods?

2024-09-30 06:31 UTC, MalasataXD commented on src/core/domain/models/Board/Board.cs
> +    #region OrderBy Methods
Same as above...

2024-09-30 06:31 UTC, MalasataXD commented on src/core/domain/models/Board/Board.cs
> +    public (IEnumerable<FilterExpression> filters, IEnumerable<OrderByExpression> orderByExpressions) GetExpressions()
Hmmm.. I think it just better to stick with getting these values from the properties instead...

2024-09-30 06:31 UTC, MalasataXD commented on src/core/domain/models/Board/values/FilterExpression.cs
> +    private static Result Validate(Expression<Func<WorkItem, bool>> expression)
Wouldn't this make them required?

2024-09-30 06:31 UTC, MalasataXD commented on src/core/domain/models/Board/values/OrderByExpression.cs
> +    private static Result Validate(Expression<Func<WorkItem, object>> expression)
Same for this one

2024-09-30 06:31 UTC, MalasataXD commented on src/core/domain/models/Board/BoardBuilder.cs
Where are the methods to create a `Board` with `filters` and `Orderby` expressions?

2024-09-30 06:31 UTC, MalasataXD commented on src/core/domain/models/Board/BoardConstants.cs
Aren't there missing some default `filters` and `OrderBy` Expressions?

2024-09-30 06:31 UTC, MalasataXD commented on src/tests/Unit/models/Board/BoardBuilderTests.cs
Where are the tests for `filters` and `OrderBy` expressions?

2024-09-30 11:15 UTC, MalasataXD approved these changes
Looks ready for merge! 🦙

2024-09-30 11:26 UTC, merged