Feature documentation
TheCodexProject/TheCodexProject-BackEnd pull request #9
Opened 2024-09-26 18:23 UTC by Grey-rgb

* Added DocumentationTitle
* Added DocumentationTitle tests

* Added DocumentationFormat
* Added DocumentationFormat tests

* Added DocumentationContent
* Added DocumentationContent tests

* Added DocumentationBuilder
* Added DocumentationBuilder tests

2024-09-26 19:15 UTC, MalasataXD requested changes
There are a few things that need looking into... But otherwise Good Job :+1:

2024-09-26 19:15 UTC, MalasataXD commented on src/core/domain/models/Documentation/Documentation.cs
The `DocumentationTitle`, `DocumentationFormat` and `DocumentationContent` properties should just have simple names, they don't need to be named like the class. This should be changed for `Title`, `Format` and `Content` instead.

2024-09-26 19:15 UTC, MalasataXD commented on src/core/domain/models/Documentation/DocumentationBuilder.cs
> +    public Result<Documentation> Build()
Isn't the format also required? What if I have some content without knowing the format. That wouldn't work.

2024-09-26 19:15 UTC, MalasataXD commented on src/core/domain/models/Documentation/values/DocumentationFormat.cs
> +            case { Length: > 5 }:
Is this including the `.` or not?

2024-09-26 19:15 UTC, MalasataXD commented on src/core/domain/models/Documentation/values/DocumentationFormat.cs
> +            case { Length: < 2 }:
Same for this one.

2024-09-26 19:15 UTC, MalasataXD commented on src/tests/Unit/models/Documentation/DocumentationBuilderTests.cs
> +        public void Create_Documentation_With_Too_Long_Format_Should_Fail()
Shouldn't this both return a `TooLong` and  "no dot" exception?

2024-09-26 19:15 UTC, MalasataXD commented on src/core/domain/models/Documentation/DocumentationBuilder.cs
> +    public Result<Documentation> Build()
Also you aren't check if the values have been set. Just if there are any exceptions in the list.

2024-09-26 19:15 UTC, MalasataXD commented on src/tests/Unit/models/Documentation/DocumentationBuilderTests.cs
Pretty sure you can create an `Documentation` without setting anything and it would still succeed.

2024-09-26 19:15 UTC, MalasataXD commented on src/tests/Unit/values/Documentation/DocumentationFormatTests.cs
> +        public void Format_Cannot_Be_Too_Short_Is_Failure()
Should it also return a "no dot" exception here?

2024-09-26 19:15 UTC, MalasataXD commented on src/tests/Unit/values/Documentation/DocumentationFormatTests.cs
> +        public void Format_Cannot_Be_Too_Long_Is_Failure()
Should it also return a "no dot" exception here?

2024-09-26 19:15 UTC, MalasataXD commented on src/tests/Unit/values/Documentation/DocumentationFormatTests.cs
> +        public void Format_Cannot_Be_Too_Short_Exception_Check()
Same as above.

2024-09-26 19:15 UTC, MalasataXD commented on src/tests/Unit/values/Documentation/DocumentationFormatTests.cs
> +        public void Format_Cannot_Be_Too_Long_Exception_Check()
Same as above

2024-09-26 19:15 UTC, MalasataXD commented on src/tests/Unit/values/Documentation/DocumentationFormatTests.cs
> +        public void Format_Contains_Dot_In_Wrong_Place_Check()
Shouldn't the exception be checked? Just to verify that you are getting the right exception for your failure.

2024-09-26 19:26 UTC, Grey-rgb commented on src/core/domain/models/Documentation/values/DocumentationFormat.cs
> +            case { Length: > 5 }:
Including the dot

2024-09-26 19:26 UTC, Grey-rgb commented on src/core/domain/models/Documentation/DocumentationBuilder.cs
> +    public Result<Documentation> Build()
Good point 👍

2024-09-26 19:27 UTC, MalasataXD commented on src/core/domain/models/Documentation/values/DocumentationFormat.cs
> +            case { Length: > 5 }:
That would be nice just to note, so it is clearly stated 😉

2024-09-27 13:05 UTC, BjarkeBP requested changes
Fix the comments in the code and add some tests to the DocumentationContent value.

2024-09-30 06:56 UTC, MalasataXD requested changes
Still a few things to be fixed. 😉

2024-09-30 06:56 UTC, MalasataXD commented on src/core/domain/exceptions/Documentation/DocumentationFormat/DocumentationFormatDoesNotFollowConventionException.cs
> +    public DocumentationFormatDoesNotFollowConventionException() : base("Format doesn't follow conventions, it must contain atleast a dot and a single character.") { }
Isn't more correct error message like this `Format doesn't follow the convention: It must start with a dot and contain at least one single character.`? I think this makes a little more sense given how it works.

2024-09-30 06:56 UTC, MalasataXD commented on src/core/domain/models/Documentation/DocumentationBuilder.cs
> +        // ? Check if there are any ProjectTitleEmptyExceptions in the errors list.
Still haven't been fixed.

2024-09-30 06:56 UTC, MalasataXD commented on src/core/domain/models/Documentation/DocumentationBuilder.cs
> +                _errors.Add(new RequiredFieldMissingException("Title is required.", new DocumentationContentEmptyException()));
Wrong message.

2024-09-30 06:56 UTC, MalasataXD commented on src/core/domain/models/Documentation/DocumentationBuilder.cs
> +                _errors.Add(new RequiredFieldMissingException("Title is required.", new DocumentationFormatEmptyException()));
Wrong message.

2024-09-30 06:56 UTC, MalasataXD commented on src/tests/Unit/models/Documentation/DocumentationBuilderTests.cs
> +        public void Create_Documentation_With_Too_Long_Format_Should_Fail()
Still haven't been fixed.

2024-09-30 06:56 UTC, MalasataXD commented on src/tests/Unit/models/Documentation/DocumentationBuilderTests.cs
Have you tested this?

2024-09-30 06:56 UTC, MalasataXD commented on src/tests/Unit/values/Documentation/DocumentationFormatTests.cs
> +        public void Format_Contains_Dot_In_Wrong_Place_Check()
Still haven't been fixed.

2024-09-30 11:38 UTC, MalasataXD approved these changes
Looks ready for merge 🐕

2024-09-30 11:55 UTC, BjarkeBP approved these changes
Looks good to me (👉ﾟヮﾟ)👉

2024-09-30 11:56 UTC, merged